name: 'Remote Repository Sync'
description: 'A GitHub Action to sync repositories with a remote source'
author: 'Repo Syncer'
inputs:
  name:
    description: 'The name of the remote repository'
    required: true
  url:
    description: 'The URL of the remote repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Git Configurations
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
      shell: bash

    - name: Add remote and fetch all branches and tags
      run: |
        git remote add ${{ inputs.name }} ${{ inputs.url }}
        git fetch ${{ inputs.name }} --tags
        git fetch ${{ inputs.name }} '+refs/heads/*:refs/remotes/${{ inputs.name }}/*'
      shell: bash

    - name: Push all branches and tags to origin
      run: |
        for branch in $(git branch -r | grep '${{ inputs.name }}/' | sed 's/${{ inputs.name }}\///'); do
          git push origin ${{ inputs.name }}/$branch:refs/heads/$branch --force
        done
        git push --tags --force
      shell: bash

branding:
  icon: 'refresh-cw'
  color: 'blue'
